// ==================== USERS ROUTES ============================

###
POST http://localhost:3003/user/cadaster
Content-Type:  application/json

{
  "name": "Gabriel",
  "email": "gabriel@gmail.com",
  "password": "12345678",
  "role": "admin"
}